### ISSUE TITLE
French SI Brochure feedback from BIPM (pages 82-104-Index)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#44] opened 2020-10-30 14:31 UTC
page | comment
-- | --
82 | 2nd bullet point in first list: replace "mètre" by "mètres"
82 | use comma as decimal separator for all  numbers
83 | 3rd bullet point from bottom: pi not in italics
83 | last bullet point from bottom : M in M(12C) in italics
82 | CIPM 2013: isolated » at beginning of line
85 | 1st bullet point following "recommande": change to 6s2  1S0  –  6s  6p  3P0
85 | 2nd bullet point: 4s   2S1/2   –   3d 2D5/2
85 | 3rd bullet point: 6s 2S1/2 – 4f 13  6s2  2F7/2
85 | 3rd bullet point : 6s2  1S0 – 6s 6p 3P0
85 | 3rd bullet point: use comma as decimal separator for all numbers
85 | last bullet point: 3s2 1S0  – 3s 3p 3P0
85 | last bullet point: use comma as decimal separator
86 | 1st bullet point:  5d10 6s 2S1/2  –  5d9 6s2 2D5/2
86 | 1st bullet point: use comma as decimal separator for all numbers
86 | 2nd bullet point: 6s 2S1/2 (F = 0, mF = 0) – 5d  2D3/2 (F = 2, mF = 0)
86 | 3rd bullet point: 5s  2S1/2 – 4d 2D5/2
86 | 4th bullet point: 5s2 1S0  –  5s 5p 3P0
86 | Resolution 1: 1st paragraph, e in italics
87 | Recommendation 2 : also here, all identification of the optical transitions have errors with the subscripts and superscripts. Please refer to the SI brochure.
87 | Recommendation 2: use the comma as decimal separator for all numbers
87 | last bullet point: accent missing on "octopôle".
88 | first bullt point: addent missing on "quadrupôle"
88 | two bullet points following "recommande": "Les valeurs" too far on the left
89 | Resolution 1, list of constants: use comma as decimal separator for the value of the Avogadro constant
90 | "Annexe 1" missing in first title
90 | "Annex 2" missing in second title
90 | 4th bullet point from bottom: h in italics
90 | 3rd bullet point from botton: pi not in italics
90 | 2nd bullet point from bottom: replace TTPW by TTPW
90 | last bullet point: M italics
91 | "Annex 3" missing in title
91 | group decimals after decimal separator  by three, for all numbers
94 | Can we keep "Partie 1" in the title, without creating a separate entry in the Table of Contents? Analogous for "Partie 2" and "Partie 3".
95 | 4th paragraph: isolated » at beginning of line
99 | first paragraph: Metrologia in italics
99 | second paragraph: Metrologia in italics
100 | 3rd paragraph: isolated » at beginning of line
100 | last paragraph: isolated « at end of line
100 | last paragraph, 5th line: wrong symbol for °K
101 | first paragraph:  isolated « at end of line
101 | 2nd paragraph: N in italics
101 | 3rd paragraph: isolated « at end of line
101 | last paragraph: isolated « at end of line
104 | entry for SUNAMCO: text wrongly distributed over columns
INDEX | The index is missing

**Comment by Intelligent2013** [comment] 2020-10-31 08:28
page | comment | to fix
-- | -- | --
82 | 2nd bullet point in first list: replace "mètre" by "mètres | adoc
82 | use comma as decimal separator for all  numbers | adoc
83 | 3rd bullet point from bottom: pi not in italics | adoc
83 | last bullet point from bottom : M in M(12C) in italics | adoc
82 | CIPM 2013: isolated » at beginning of line | adoc
85 | 1st bullet point following "recommande": change to 6s2  1S0  –  6s  6p  3P0 | adoc
85 | 2nd bullet point: 4s   2S1/2   –   3d 2D5/2 | adoc
85 | 3rd bullet point: 6s 2S1/2 – 4f 13  6s2  2F7/2 | adoc
85 | 3rd bullet point : 6s2  1S0 – 6s 6p 3P0 | adoc
85 | 3rd bullet point: use comma as decimal separator for all numbers | adoc
85 | last bullet point: 3s2 1S0  – 3s 3p 3P0 | adoc
85 | last bullet point: use comma as decimal separator | adoc
86 | 1st bullet point:  5d10 6s 2S1/2  –  5d9 6s2 2D5/2 | adoc
86 | 1st bullet point: use comma as decimal separator for all numbers | adoc
86 | 2nd bullet point: 6s 2S1/2 (F = 0, mF = 0) – 5d  2D3/2 (F = 2, mF = 0) | adoc
86 | 3rd bullet point: 5s  2S1/2 – 4d 2D5/2 | adoc
86 | 4th bullet point: 5s2 1S0  –  5s 5p 3P0 | adoc
86 | Resolution 1: 1st paragraph, e in italics | adoc
87 | Recommendation 2 : also here, all identification of the optical transitions have errors with the subscripts and superscripts. Please refer to the SI brochure. | adoc
87 | Recommendation 2: use the comma as decimal separator for all numbers | adoc
87 | last bullet point: accent missing on "octopôle". | adoc
88 | first bullt point: addent missing on "quadrupôle" | adoc
88 | two bullet points following "recommande": "Les valeurs" too far on the left | xslt
89 | Resolution 1, list of constants: use comma as decimal separator for the value of the Avogadro constant | adoc
90 | "Annexe 1" missing in first title | adoc
90 | "Annex 2" missing in second title | adoc
90 | 4th bullet point from bottom: h in italics | adoc
90 | 3rd bullet point from botton: pi not in italics | adoc
90 | 2nd bullet point from bottom: replace TTPW by TTPW | adoc
90 | last bullet point: M italics | adoc
91 | "Annex 3" missing in title | adoc
91 | group decimals after decimal separator  by three, for all numbers | adoc
94 | Can we keep "Partie 1" in the title, without creating a separate entry in the Table of Contents? Analogous for "Partie 2" and "Partie 3". | adoc
95 | 4th paragraph: isolated » at beginning of line | adoc
99 | first paragraph: Metrologia in italics | adoc
99 | second paragraph: Metrologia in italics | adoc
100 | 3rd paragraph: isolated » at beginning of line | adoc
100 | last paragraph: isolated « at end of line | adoc
100 | last paragraph, 5th line: wrong symbol for °K | adoc
101 | first paragraph:  isolated « at end of line | adoc
101 | 2nd paragraph: N in italics | adoc
101 | 3rd paragraph: isolated « at end of line | adoc
101 | last paragraph: isolated « at end of line | adoc
104 | entry for SUNAMCO: text wrongly distributed over columns | adoc
INDEX | The index is missing | ?

**Comment by Intelligent2013** [comment] 2020-10-31 14:07
Regarding issue

page | comment | to fix
-- | -- | --
88 | two bullet points following "recommande": "Les valeurs" too far on the left | adoc or xslt

In the  document there are a few definition lists (`dl`) in list items:

### Resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/97781081-0227ac00-1b9a-11eb-906f-05b666a2d3a5.png)

### Source PDF:
![изображение](https://user-images.githubusercontent.com/5559926/97781127-77937c80-1b9a-11eb-9d72-6afdfa9f7498.png)


### Resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/97781096-313e1d80-1b9a-11eb-8c0c-17a6c67f6dca.png)


### Source PDF:
![изображение](https://user-images.githubusercontent.com/5559926/97781151-9134c400-1b9a-11eb-8903-c964e8812bdb.png)

Second example in the source PDF is centered definition list. If we add a left margin to `dl` in list items, then the resulted PDF looks ok:

### Updated resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/97781271-3485d900-1b9b-11eb-920d-019bb1f256ef.png)

BUT we get the same margin for first example:

### Updated resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/97781233-f7b9e200-1b9a-11eb-93fe-080e3e9ff7c1.png)

**Comment by opoudjis** [comment] 2020-11-01 04:47
I reject the notion of centering dl's: Metanorma is not Word, and is not going to support open-ended free formatting. In any case, what is happening here is not a centered dl, it is a dl nested within a list entry, so:

````
* Molecules blah blah
+
----
Les valeurs:: f_a1_ ...
----
````

Won't an embedded `ul/li/dl` take care of this?

**Comment by Intelligent2013** [comment] 2020-11-01 09:50
> Won't an embedded ul/li/dl take care of this?

In this case it's enough.
But there is case with similar markup:

```adoc
. Les unités photométriques peuvent être définies comme suit:
+
--
*_Bougie nouvelle_* (unité d’intensité lumineuse).:: La grandeur de la bougie nouvelle est telle
que la brillance du radiateur intégral à la température de solidification du platine soit de
60 bougies nouvelles par centimètre carré.

*_Lumen nouveau_* (unité de flux lumineux).:: Le lumen nouveau est le flux lumineux émis dans
l’angle solide unité (stéradian) par une source ponctuelle uniforme ayant une intensité
lumineuse de 1 bougie nouvelle.
--
```

And it shows in source PDF without indent:
![изображение](https://user-images.githubusercontent.com/5559926/97799541-e8d93b00-1c3f-11eb-98f8-d6238cf1b1e1.png)

@ronaldtse It's ok if we'll show it with indents? :
![изображение](https://user-images.githubusercontent.com/5559926/97799655-6ef58180-1c40-11eb-8994-f629f3379fc7.png)

**Comment by opoudjis** [comment] 2020-11-01 10:18
Or alternatively, don't treat it as a definition list at all: they haven't...

**Comment by manuel489** [comment] 2020-11-02 20:13
> 82 | 2nd bullet point in first list: replace "mètre" by "mètres | adoc

> 83 | last bullet point from bottom : M in M(12C) in italics | adoc

> 82 | CIPM 2013: isolated » at beginning of line | adoc

> 86 | Resolution 1: 1st paragraph, e in italics | adoc

> 87 | last bullet point: accent missing on "octopôle". | adoc

> 88 | first bullt point: addent missing on "quadrupôle" | adoc

> 90 | 2nd bullet point from bottom: replace TTPW by TTPW | adoc

> 90 | last bullet point: M italics | adoc

> 95 | 4th paragraph: isolated » at beginning of line | adoc

> 99 | first paragraph: Metrologia in italics | adoc

> 99 | second paragraph: Metrologia in italics | adoc

> 100 | 3rd paragraph: isolated » at beginning of line | adoc

> 100 | last paragraph: isolated « at end of line | adoc

> 100 | last paragraph, 5th line: wrong symbol for °K | adoc

> 101 | first paragraph: isolated « at end of line | adoc

> 101 | 2nd paragraph: N in italics | adoc

> 101 | 3rd paragraph: isolated « at end of line | adoc

> 101 | last paragraph: isolated « at end of line | adoc

> 104 | entry for SUNAMCO: text wrongly distributed over columns | adoc

All fixed.


> 90 | "Annexe 1" missing in first title | adoc

> 90 | "Annex 2" missing in second title | adoc

> 91 | "Annex 3" missing in title | adoc

I have put "Annexe 1", "Annexe 2" and "Annexe 3" explicitly in the corresponding section titles.


> 94 | Can we keep "Partie 1" in the title, without creating a separate entry in the Table of Contents? Analogous for "Partie 2" and "Partie 3". | adoc

Added "Partie 1" in title. Fixed.



> 83 | 3rd bullet point from bottom: pi not in italics | adoc

> 90 | 4th bullet point from bottom: h in italics | adoc

> 90 | 3rd bullet point from botton: pi not in italics | adoc

Not fixable by markup.


> 82 | use comma as decimal separator for all numbers | adoc

> 85 | 3rd bullet point: use comma as decimal separator for all numbers | adoc

> 85 | last bullet point: use comma as decimal separator | adoc

> 86 | 1st bullet point: use comma as decimal separator for all numbers | adoc

> 87 | Recommendation 2: use the comma as decimal separator for all numbers | adoc

> 89 | Resolution 1, list of constants: use comma as decimal separator for the value of the Avogadro constant | adoc

> 91 | group decimals after decimal separator by three, for all numbers | adoc

I believe these are suposed to be handled automatically.


> 85 | 1st bullet point following "recommande": change to 6s2 1S0 – 6s 6p 3P0 | adoc

> 85 | 2nd bullet point: 4s 2S1/2 – 3d 2D5/2 | adoc

> 85 | 3rd bullet point: 6s 2S1/2 – 4f 13 6s2 2F7/2 | adoc

> 85 | 3rd bullet point : 6s2 1S0 – 6s 6p 3P0 | adoc

> 85 | last bullet point: 3s2 1S0 – 3s 3p 3P0 | adoc

> 86 | 1st bullet point: 5d10 6s 2S1/2 – 5d9 6s2 2D5/2 | adoc

> 86 | 2nd bullet point: 6s 2S1/2 (F = 0, mF = 0) – 5d 2D3/2 (F = 2, mF = 0) | adoc

> 86 | 3rd bullet point: 5s 2S1/2 – 4d 2D5/2 | adoc

> 86 | 4th bullet point: 5s2 1S0 – 5s 5p 3P0 | adoc

> 87 | Recommendation 2 : also here, all identification of the optical transitions have errors with the subscripts and superscripts. Please refer to the SI brochure. | adoc

These cases are rendering well in HTML but not in PDF. @Intelligent2013?


> 88 | two bullet points following "recommande": "Les valeurs" too far on the left | adoc or xslt

In HTML renders fine, but not in PDF. @Intelligent2013?


> INDEX | The index is missing | ?

I believe this refers to the lack of an alphabetical index in the generated output. @opoudjis ?

**Comment by manuel489** [comment] 2020-11-02 20:13
Fixes are in https://github.com/metanorma/bipm-si-brochure/pull/45

**Comment by opoudjis** [comment] 2020-11-17 12:51
> INDEX | The index is missing | ?
> I believe this refers to the lack of an alphabetical index in the generated output. @opoudjis ?

Yes, and I got bad news for you.

Yes, we can add index markup to Metanorma: we have done it for IETF. I would not want to be @Intelligent2013 implementing it, and I'd be assiduously avoiding implementing it myself. And index generation is going to be a horrific amount of markup for you to do.

@ronaldtse I'd like for you to confirm that indexing is a requirement, and it's not going to be quick if we do do it.

**Comment by ronaldtse** [comment] 2020-11-17 14:12
@opoudjis Yes, the index is a requirement. We've been avoiding it for quite some time and this seems like a good time to introduce this. I assume the index will be included in Presentational XML.

**Comment by opoudjis** [comment] 2020-11-17 14:24
> I assume the index will be included in Presentational XML.

... Gee. Thanks.

Presumably it will be realised in Presentation XML as the page-only cross-references we have already been bludgeoned by BIPM into producing.

**Comment by manuel489** [comment] 2020-12-01 23:06
Based on the latest PDF provided by @opoudjis: [si-brochure-fr(12-01).pdf](https://github.com/metanorma/bipm-si-brochure/files/5622920/si-brochure-fr.12-01.pdf)

Issues fixed recently:

page | comment | issue
-- | -- | --
85 | 3rd bullet point : 6s2  1S0 – 6s 6p 3P0 | fixed in https://github.com/metanorma/bipm-si-brochure/pull/59
86 | 2nd bullet point: 6s 2S1/2 (F = 0, mF = 0) – 5d  2D3/2 (F = 2, mF = 0) | fixed in https://github.com/metanorma/bipm-si-brochure/pull/59
90 | 4th bullet point from bottom: h in italics | fixed in https://github.com/metanorma/bipm-si-brochure/pull/59


Remaining issues:

page | comment | issue
-- | -- | --
83 | last bullet point from bottom : M in M(12C) in italics | not fixed
90 | last bullet point: M italics | not fixed
101 | 2nd paragraph: N in italics | not fixed
INDEX | The index is missing | not fixed

Additional issues that weren't before:

* Italics was removed for the `N` letter in stem blocks (`stem:[N]`):
![issue1](https://user-images.githubusercontent.com/33627611/100806179-65f5fc80-3406-11eb-94fa-310fbc98957c.PNG)

* Cursive `K` in math (`stem:[cc "K"]) is not rendering as expected:
*Generated:*
![issue2](https://user-images.githubusercontent.com/33627611/100806189-69898380-3406-11eb-8e22-f1a46f48afb9.PNG)
*Original:*
![issue2-original](https://user-images.githubusercontent.com/33627611/100806562-0c420200-3407-11eb-94cf-debe1dd2a1ef.PNG)

**Comment by Intelligent2013** [comment] 2020-12-02 12:09
> Cursive K in math (stem:[cc "K"]) is not rendering as expected:

Very strange. In my environment (Win7) it generated ok:
![изображение](https://user-images.githubusercontent.com/5559926/100870413-a2c9fe00-34af-11eb-83be-f082375d6407.png)

Looks like it occurs for `<mstyle mathvariant="script">....`, but one font `STIX Two Math` is using for all maths...

**Comment by opoudjis** [comment] 2020-12-04 12:10
@Intelligent2013 Since I generated the PDF, the issue is my side. Could you please tell me what to check?

**Comment by manuel489** [comment] 2020-12-04 19:17
Two remaining issues:

page | comment | issue
-- | -- | --
101 | 2nd paragraph: N in italics | not fixed
INDEX | The index is missing | not fixed

**Comment by anermina** [comment] 2020-12-08 12:20
Issue https://github.com/metanorma/metanorma-bipm/issues/67 is opened to address adding index. Closing this one.

**Closed by anermina** 2020-12-08 12:20 UTC
Labels: bug
