### ISSUE TITLE
BIPM requested fixes 2: small spaces between closing parenthesis and unit symbols disappeared

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#222] opened 2024-02-22 08:00 UTC
From Michael Stock:

We also found that small spaces between closing parenthesis and unit symbols, which existed in the previous version, have disappeared:
- Page 18 (English version), first equation: “(…) s”
- Page 18 (English version), second equation: “(…) m-2”
- Page 19 (English version), first equation: “(…) s-1”
- Page 19 (English version), third equation: “(…) kg”
- Page 21 (English version), fourth equation: “(…) kg”
- The same applies to the equivalent equations in the French version.

**Comment by ronaldtse** [comment] 2024-02-22 08:30
Is this a UnitsML rendering issue?

**Comment by opoudjis** [comment] 2024-02-22 15:17
I was meticulous about putting in thin spaces between number and unit, I would assume they have indeed gone away.

**Comment by opoudjis** [comment] 2024-02-22 15:37
I'm not sure I can find this thing space in https://github.com/plurimath/asciimath2unitsml

The version of the brochure I last compiled May 2023 has:

````
   <mrow>
      <mo>(</mo>
      <mfrac>
        <mi>c</mi>
        <mn>299792458</mn>
      </mfrac>
      <mo>)</mo>
    </mrow>
    <mrow xref="U_NISTu3"><mi mathvariant="normal">s</mi></mrow>
````

No space, and I strongly suspect any space there was an artefact of the MathML rendering engine, not us.

You're going to need to produce older XML and PDF for us to investigate this.

**Comment by anermina** [comment] 2024-02-22 22:26
The issue is not related to spaces after the closing parentheses only, but rather to spaces before the `unitsml` symbols in general.

This is an archive I have from September 13th, 2022:
[Archive.zip](https://github.com/metanorma/bipm-si-brochure/files/14379910/Archive.zip)

Back then, the output was as follows:
![image](https://github.com/metanorma/bipm-si-brochure/assets/55683568/8ede6841-3a77-480f-8ea8-16957c1168fa)

Corresponding XML for the part `1 m`:
````
<mn>1</mn><mo rspace="thickmathspace">&#x2062;</mo><mrow xref="U_NISTu1"><mi mathvariant="normal">m</mi></mrow>
````

The current output is:
![image](https://github.com/metanorma/bipm-si-brochure/assets/55683568/d2a807b5-b139-4ce0-9dd6-c5b8e21c6bca)

**Comment by ronaldtse** [comment] 2024-02-23 02:38
It looks like an issue with PDF MathML rendering? Ping @Intelligent2013

**Comment by ronaldtse** [comment] 2024-02-23 02:39
Or is this to do with UnitsML rendering in MathML? Ping @suleman-uzair

**Comment by suleman-uzair** [comment] 2024-02-23 12:11
> The issue is not related to spaces after the closing parentheses only, but rather to spaces before the unitsml symbols in general.

@ronaldtse As @opoudjis mentioned
> I’m not sure I can find this thing space in https://github.com/plurimath/asciimath2unitsml
and
> No space, and I strongly suspect any space there was an artefact of the MathML rendering engine, not us.

**Unitsml-Ruby** does not insert spaces by default, do we need to insert spaces explicitly, if we do need, then should we add spaces before each **Unitsml** symbol by default or an argument for it? for example,

`Unitsml.parse(“m”).to_mathml(rspace: (true or false))`

**Comment by opoudjis** [comment] 2024-02-27 09:18
I recommend you implement what I had implemented, in postprocessing.

The README in https://github.com/plurimath/asciimath2unitsml documents this:

> The gem follows the MathML Units convention of inserting a spacing invisible times operator (`<mo rspace='thickmathspace'>⁢</mo>`) between any numbers (`<mn>`) and unit expressions in MathML, and representing units in MathML as non-italic variables (`<mi mathvariant='normal'>`).

> Space is not inserted between a number and a unit expression, when that unit expression wholly consists of punctuation: 1 m, 1 °C, but 9° 7′ 22″.

That behaviour is realised in https://github.com/plurimath/asciimath2unitsml/blob/24d409960e0971034a2554a2ed2d2960efceba86/lib/asciimath2unitsml/parse.rb#L20  :

````
def MathML2UnitsML(xml)
      xml.is_a? String and xml = Nokogiri::XML(xml)
      xml.xpath(".//m:mtext", "m" => MATHML_NS).each do |x|
        next unless %r{^unitsml\(.+\)$}.match?(x.text)

        text = x.text.sub(%r{^unitsml\((.+)\)$}m, "\\1")
        units, origtext, normtext, quantity, name, symbol, multiplier =
          parse(text)
        rendering = if symbol
                      embeddedmathml(asciimath2mathml(symbol))
                    else
                      mathmlsymbol(units, false, multiplier)
                    end
        x.replace("#{delimspace(rendering, x)}"\
                  "<mrow xref='#{unit_id(origtext)}'>#{rendering}</mrow>\n"\
                  "#{unitsml(units, origtext, normtext, quantity, name)}")
      end
      dedup_ids(xml)
    end

    # if previous sibling's last descendent non-whitespace is MathML and
    # mn or mi, no space
    def delimspace(rendering, elem)
      prec_text_elem =
        elem.xpath("./preceding-sibling::*[namespace-uri() = '#{MATHML_NS}']/"\
                   "descendant::text()[normalize-space()!='']"\
                   "[last()]/parent::*").last
      return "" if prec_text_elem.nil? ||
        !%w(mn mi).include?(prec_text_elem&.name)

      text = HTMLEntities.new.encode(Nokogiri::XML("<mrow>#{rendering}</mrow>")
        .text.strip)
      if /\p{L}|\p{N}/.match?(text)
        "<mo rspace='thickmathspace'>&#x2062;</mo>"
      else "<mo>&#x2062;</mo>"
      end
    end
````

The `#{delimspace(rendering, x)}` is the  `<mo rspace='thickmathspace'>&#x2062;</mo>` or `<mo>&#x2062;</mo>` or "".  

* If the unitsml is preceded by mi or mn, and the unitsml contains a number or letter, they are separated by `<mo rspace='thickmathspace'>&#x2062;</mo>`
*  If the unitsml is preceded by mi or mn, and the unitsml contains a number or letter (e.g. °), it gets `<mo>&#x2062;</mo>`. I don't know now how that works, but without the rspace, the separation collapses in MathML to not showing a space: `<mn>9</mn><mo>&#x2062;</mo><mi>°</mi>` renders apparently as just 9°.
* If the unitsml is preceded by anything else (or nothing), it gets "".

The four initial test cases in https://github.com/plurimath/asciimath2unitsml/blob/24d409960e0971034a2554a2ed2d2960efceba86/spec/conv_spec.rb all deal with this kind of spacing.

**Comment by ronaldtse** [comment] 2024-04-06 02:16
@suleman-uzair @opoudjis we need to handle this issue ASAP. What's the hold up?

**Comment by suleman-uzair** [comment] 2024-04-08 08:10
@ronaldtse, I have just released a version for **Plurimath** `0.8.0` containing fix for this issue.

**Comment by opoudjis** [comment] 2024-04-08 14:15
OK, We have a pending release, but the Plurimath dependency is in HTML2Doc. I'm assuming nothing has broken in the major release of Plurimath?

**Comment by opoudjis** [comment] 2024-04-08 14:32
Result is one change to an isodoc spec file. I am holding off on releasing html2doc update, to upgrade plurimath, until after the current release clears.

**Comment by opoudjis** [comment] 2024-04-09 02:00
Blocked by https://github.com/plurimath/plurimath/issues/236

**Comment by opoudjis** [comment] 2024-04-09 12:59
Compiling now, but not seeing the spaces...

**Comment by opoudjis** [comment] 2024-04-16 10:37
Has been implemented successfully in Plurimath.

**Comment by ronaldtse** [comment] 2024-12-17 04:35
Need urgent help here from @suleman-uzair.

**Comment by jmilesBIPM** [comment] 2024-12-17 09:35
@suleman-uzair, the space after the bracket is fine in the above preview. But the spaces in the long number "1.602 176 634"  are missing!

**Comment by ronaldtse** [comment] 2024-12-17 10:09
@suleman-uzair I believe this behavior occurs in our PDF generation of the MathML. The problem is described by @anermina here:
* https://github.com/metanorma/bipm-si-brochure/issues/222#issuecomment-1960430876

Where it seems that we need to somehow insert "spacing" between numbers and the parentheses. I don't know if this is a Batik (our PDF math rendering engine) bug or is there something we can do at the Plurimath level.

So the options are:

1. Batik bug - we need to get someone to fix it.
2. Plurimath - if we can insert some spacing. However, I don't want to break our very clean implementation of MathML with these random spaces.

As to @jmilesBIPM 's question on number formatting (spaces between numbers)

* @suleman-uzair I don't think plurimath.org (which is where your screenshot is from) supports number formatting?
* Currently the declaration of number formatting style is defined in Metanorma, then passed to Plurimath for actual formatting of numbers inside MathML.
* @suleman-uzair can we somehow enable number formatting (and defining) on plurimath.org?

**Comment by suleman-uzair** [comment] 2024-12-17 11:19
> if we can insert some spacing.

@ronaldtse, I think these spaces should not be handled in **Plurimath**, we already have number formatting for this.

> I don’t think [plurimath.org](http://plurimath.org/) (which is where your screenshot is from) supports number formatting?

Yes, [plurimath.org](http://plurimath.org/) doesn’t support number formatting yet.

> can we somehow enable number formatting (and defining) on [plurimath.org](http://plurimath.org/)?

Number formatting is not available in plurimath-js yet, I’ll look into it once it is available.

**Comment by ronaldtse** [comment] 2024-12-17 11:27
Doesn’t Plurimath do number formatting (as with variable formatting)? There was the topic of Matt presentations style we previously discussed, and the proper place to do it is in MathML (ie. A layer above MathML).

**Comment by suleman-uzair** [comment] 2024-12-17 12:04
> Doesn’t Plurimath do number formatting (as with variable formatting)?

@ronaldtse, Are you referring to plurimath/plurimath#129?

Also, we can add a configuration module to set the `number formatter` for all the examples processed via **Plurimath**.
Let me know if this implementation will be helpful.

**Comment by manuelfuenmayor** [comment] 2024-12-17 12:58
> @manuelfuenmayor, I have just tested the example using Plurimath version 0.8.18, and the spaces are there (see the attached screenshot below), can you provide the generated MathML and/or the input and the Plurimath version you are using so I can troubleshoot it further?

@suleman-uzair I am using Plurimath 0.8.18, however, I will share the corresponding MathML in short. In the meantime, there are further details about the issue in this ticket: https://github.com/plurimath/plurimath/issues/314.

Also, I missed to tell that this issue is only shown in PDF output, spacing in HTML looks fine.

**Comment by manuelfuenmayor** [comment] 2024-12-17 13:04
Here's the MathML for the formula I've shared:
```
<formula id="_36937f89-5657-3191-3557-84c8e243ad73" unnumbered="true"><stem block="true" type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML">
  <mstyle displaystyle="true">
    <mn>1</mn>
    <mo rspace="thickmathspace">⁢</mo>
    <mrow xref="U_NISTu4">
      <mstyle mathvariant="normal">
        <mi>A</mi>
      </mstyle>
      
      
      
    </mrow>
    <mo>=</mo>
    <mo rspace="thickmathspace">⁢</mo>
    <mrow>
      <mo>(</mo>
      <mfrac>
        <mi>e</mi>
        <mrow>
          <mn>1.602 176 634</mn>
          <mo>×</mo>
          <msup>
            <mn>10</mn>
            <mrow>
              <mo>−</mo>
              <mn>19</mn>
            </mrow>
          </msup>
        </mrow>
      </mfrac>
      <mo>)</mo>
    </mrow>
    <mrow xref="U_NISTu3e-1/1">
      <msup>
        <mstyle mathvariant="normal">
          <mi>s</mi>
        </mstyle>
        <mrow>
          <mo>−</mo>
          <mn>1</mn>
        </mrow>
      </msup>
      
      
    </mrow>
  </mstyle>
</math><asciimath>1 "unitsml(A)" = (e/(1.602176634 xx 10^(-19))) "unitsml(s^(-1))"</asciimath></stem></formula>
```

This is the formula taken from PDF output:
![pdf-formula](https://github.com/user-attachments/assets/0015b5b1-6696-47df-b15f-7ee579ae45f6)

**Comment by manuelfuenmayor** [comment] 2024-12-17 13:10
In regard to the spacing between numbers, we have to set `:number-presentation-formula: default` in the document to enable the format.  [Plurimath.org](http://plurimath.org/) doesn't show it, currently.

**Comment by suleman-uzair** [comment] 2024-12-17 14:17
> we have to set :number-presentation-formula: default in the document to enable the format.

@manuelfuenmayor, I see the following two issues discussed here.
1. Spaces between numbers
a. can you confirm if the spaces between numbers issue will be fixed with the `:number-presentation-formula: default `argument in the document? or is there any implementation required?
2. Missing spaces in the PDF rendering
a. As @opoudjis mentioned in [plurimath/plurimath#314](https://github.com/plurimath/plurimath/issues/314), this issue is related to **PDF** rendering specifically.
b. We can go with the option of adding some extra `mrow` wrappers, disturbing the current structure of **MathML** if needed.

cc: @ronaldtse

**Comment by manuelfuenmayor** [comment] 2024-12-17 14:45
> can you confirm if the spaces between numbers issue will be fixed with the :number-presentation-formula: default argument in the document? or is there any implementation required?

Yes, the spacing between numbers gets fixed by adding `:number-presentation-formula: default` to the document attributes list.

**Comment by manuelfuenmayor** [comment] 2024-12-17 14:53
> Missing spaces in the PDF rendering
a. As @opoudjis mentioned in plurimath/plurimath#314, this issue is related to PDF rendering specifically.

Yes, the issue is shown in PDF output specifically. Perhaps @Intelligent2013 could help us in this case?

**Comment by Intelligent2013** [comment] 2024-12-17 16:13
I'll see what's happened.

**Comment by Intelligent2013** [comment] 2024-12-17 17:40
On my machine I've found old Presentation XML (June 15, 2023) and generated PDF:
![image](https://github.com/user-attachments/assets/f24beb63-a9c5-4c73-b6fb-591560ad4ea2)
```xml
<formula id="_41ea4660-26a9-86e4-f1c7-4db46e95f6fc" unnumbered="true">
	<stem type="MathML">
		<math xmlns="http://www.w3.org/1998/Math/MathML">
			<mn>1</mn>
			<mo rspace="thickmathspace">⁢</mo>
			<mrow xref="U_NISTu1">
				<mi mathvariant="normal">m</mi>
			</mrow>
			<mo>=</mo>
			<mfenced open="(" close=")">
				<mrow>
					<mfrac>
						<mrow>
							<mi>c</mi>
						</mrow>
						<mrow>
							<mn>299 792 458</mn>
						</mrow>
					</mfrac>
				</mrow>
			</mfenced>
			<mo rspace="thickmathspace">⁢</mo>
			<mrow xref="U_NISTu3">
				<mi mathvariant="normal">s</mi>
			</mrow>
...
```


Latest todays PDF:
![image](https://github.com/user-attachments/assets/9cf4fc44-a9e6-48de-a92e-7ba614e73a38)

```xml
<formula id="_c7858073-453e-a4f2-e8be-77b931b58c62_si-brochure-en" unnumbered="true">
	<stem block="true" type="MathML">
		<math xmlns="http://www.w3.org/1998/Math/MathML">
			<mstyle displaystyle="true">
				<mn>1</mn>
				<mo rspace="thickmathspace">⁢</mo>
				<mrow xref="U_NISTu1">
					<mstyle mathvariant="normal">
						<mi>m</mi>
					</mstyle>
				</mrow>
				<mo>=</mo>
				<mo rspace="thickmathspace">⁢</mo>
				<mrow>
					<mo>(</mo>
					<mfrac>
						<mi>c</mi>
						<mn>299 792 458</mn>
					</mfrac>
					<mo>)</mo>
				</mrow>
				<mrow xref="U_NISTu3">
					<mstyle mathvariant="normal">
						<mi>s</mi>
					</mstyle>
				</mrow>
...
```

In the latest XML there isn't 2nd `<mo rspace="thickmathspace">⁢</mo>` after `(`:
```xml
mrow>
      <mo>(</mo>
      <mfrac>
        <mi>c</mi>
        <mn>299 792 458</mn>
      </mfrac>
      <mo>)</mo>
    </mrow>
     <mo rspace="thickmathspace">⁢</mo>
    <mrow xref="U_NISTu3">
      <mstyle mathvariant="normal">
        <mi>s</mi>
      </mstyle>
```
Just for experiment I've added it, and PDF renders ok after that:

![image](https://github.com/user-attachments/assets/53072e2a-75be-4867-8013-d260bd124309)

**Comment by manuelfuenmayor** [comment] 2024-12-18 05:18
@Intelligent2013 so... Are you going to apply the update to fix the issue?

**Comment by Intelligent2013** [comment] 2024-12-18 05:43
> @Intelligent2013 so... Do you think this issue is addressable by you or should be addressed by someone else?

@manuelfuenmayor  I think this MathML generation issue, because previously the MathML was ok.

Math in PDF generates by jEuclid  (14 years ago solution)  without using of Batik. Currently jEuclid  doesn't support by someone.  I don't have efforts and knowledge to update it. If someone have any ideas about another solution how to put Math into PDF, welcome. I see only one solution - generate SVG (with `path` (curves) or `text` elements (preferable)) by some tool and put it into XML.

**Comment by ronaldtse** [comment] 2024-12-18 10:42
@suleman-uzair we need urgent help here. Probably we need Plurimath to be able to output the 2nd `<mo rspace="thickmathspace">⁢</mo>`.

Also, the wiggly equals sign probably should have space between the sign as well.

**Comment by ronaldtse** [comment] 2024-12-19 07:53
This fix has been merged in plurimath:
* https://github.com/plurimath/plurimath/pull/317

Release is underway.

**Comment by manuelfuenmayor** [comment] 2024-12-19 15:04
Fix confirmed

**Closed by manuelfuenmayor** 2024-12-19 15:04 UTC
Labels: bug
